import {poems,masteryNames} from './poems.js?v=29';
import {termNotes} from './terms.js?v=29';
import {scheduleReview,createDailyTasks,localDateKey} from './review.js?v=29';
import {storage} from './storage.js?v=29';
import {gameModes,createGameRound,createPoemGameRound,pointsForAnswer,levelForPoints,blankForPoem} from './games.js?v=29';
import {adventureZones,characters,zoneUnlocked,zoneProgress,poemAdventureStatus,dueSoon,rhythmGuide,meaningChallenge,rewardForPoem,addPoemReward,continueRoute,contextLabel,parentAdvice} from './adventure.js?v=29';

let state=storage.load(),route=location.hash.slice(1)||'home',previousRoute=route,session={};
const $=s=>document.querySelector(s),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const save=()=>storage.save(state),go=r=>{location.hash=r};
function shuffledCopy(items){const copy=[...items];for(let i=copy.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[copy[i],copy[j]]=[copy[j],copy[i]]}if(copy.length>1&&copy.every((item,i)=>item===items[i]))copy.push(copy.shift());return copy}
addEventListener('hashchange',()=>{state.positions=state.positions||{};state.positions[previousRoute]=scrollY;previousRoute=route=location.hash.slice(1)||'home';save();render();requestAnimationFrame(()=>scrollTo(0,state.positions?.[route]||0))});

const ASSET_VERSION='29';
const sceneFiles=Object.fromEntries(poems.map(p=>[p.id,`/images/${p.id}.webp?v=${ASSET_VERSION}`]));
const imageError=`onerror="this.parentElement.classList.add('image-missing');this.remove()"`;
const icon=(p,i=0)=>`<figure class="scene" data-poem="${esc(p.title)}"><img src="${sceneFiles[p.id]}" alt="${p.images[i%p.images.length].alt}" width="360" height="240" loading="eager" decoding="async" ${imageError}><figcaption>${p.imagery[i%p.imagery.length]}</figcaption></figure>`;
function sceneVisual(p,hideCaption=false){return `<figure class="poem-scene-hero" data-poem="${esc(p.title)}"><img src="${sceneFiles[p.id]}" alt="${p.title}诗意中国风画面" width="720" height="480" loading="eager" decoding="async" ${imageError}>${hideCaption?'':`<figcaption><span>原创诗意插画</span><b>画面线索：${p.imagery.join('、')}</b></figcaption>`}</figure>`}
function role(key,text){const c=characters[key];return `<aside class="role-line role-${key}"><i>${c.mark}</i><div><b>${c.name}</b><span>${text||c.line}</span></div></aside>`}
function nav(){let active=name=>route===name||route.startsWith(`${name}/`)?' class="active"':'';return `<header><a class="brand" href="#home"><span>诗</span><b>诗画小书童</b></a><nav aria-label="主导航"><a href="#today"${active('today')}><i>今</i>今日</a><a href="#poems/all"${active('poems')||active('review')}><i>选</i>选诗</a><a href="#map"${active('map')}><i>图</i>地图</a><a href="#games"${active('games')||active('play')}><i>游</i>游戏</a><a href="#tree"${active('tree')}><i>藏</i>收藏</a></nav><div class="header-tools"><a href="#studio">创作</a><a href="#parent">家长</a><a href="#settings" aria-label="设置">设置</a></div></header>`}
function shell(content,title=''){document.body.classList.toggle('reduce-motion',state.settings.reduceMotion);document.body.classList.toggle('eye-care',state.settings.eyeCare);return `${nav()}<main id="main" class="container ${state.settings.font==='large'?'large':''}">${title?`<h1>${title}</h1>`:''}${content}</main><footer><span>不设排行榜 · 不收集真实姓名 · 学习记录只保存在这台设备</span><span>原创诗意插画已内置，可离线使用</span></footer>`}

function ensureGuest(){if(!state.profile)state.profile={nickname:'小书童',grade:3,goal:'复习一二年级 + 趣味预习三年级',guest:true};save()}
function ensureDaily(){const day=localDateKey(),valid=state.daily?.date===day&&state.daily.tasks?.length===3&&state.daily.tasks.some(t=>t.mode==='new')&&state.daily.tasks.filter(t=>t.mode==='review').length===2;if(!valid){state.daily={date:day,tasks:createDailyTasks(poems,state.progress,3)};save()}}
function practiceStep(practice=''){if(practice.includes('排序'))return 4;if(practice.includes('填空'))return 5;if(practice.includes('情境'))return 6;if(practice.includes('背诵'))return 7;return 1}
function taskStartRoute(task){return task.mode==='review'?`learn/${task.poemId}/${practiceStep(task.practice)}`:`learn/${task.poemId}`}

function home(){ensureDaily();const due=dueSoon(state.progress),resume=continueRoute(state),points=state.rewards?.points||0,newTask=state.daily.tasks.find(t=>t.mode==='new'),reward=newTask?rewardForPoem(poems.find(p=>p.id===newTask.poemId)):null;return shell(`
 <section class="adventure-home">
  <div class="adventure-copy"><span class="eyebrow">二升三 · 每天 8—10 分钟</span><h1>今天去诗里<br><em>冒一次险</em></h1><p>${due?`有 ${due} 首诗快要忘记了，快去把它们找回来。`:'先找回两首旧诗，再认识一首新诗。'}</p>
   <section class="today-brief" aria-label="今日任务"><b>今天只做三件事</b><div><span><i>1</i>学习 1 首新诗</span><span><i>2</i>复习 2 首旧诗</span><span><i>时</i>约 8—10 分钟</span><span><i>奖</i>${reward?reward.piece:'获得诗词卡和画卷碎片'}</span></div></section>
   <a id="startAdventure" class="button primary hero-primary" href="#today">开始今日诗词冒险</a>${resume?`<a class="button continue-button" href="#${resume}">继续上次学习</a>`:''}
  </div>
  <figure class="adventure-hero-art"><img src="${sceneFiles[newTask?.poemId||'hua']}" alt="今日诗词冒险画面" width="720" height="480"><figcaption><span>诗仙信使带来新任务</span><b>${newTask?`今天会遇见《${poems.find(p=>p.id===newTask.poemId)?.title}》`:'完成任务，修复一幅诗意画卷'}</b><small>已收藏 ${state.collections?.poemCards?.length||0} 张诗词卡 · ${points} 片诗叶</small></figcaption></figure>
 </section>
 ${!state.guideSeen?`<section class="first-guide">${role('scholar','看画、听诗、闯关，做完就能获得诗词收藏。')}<button id="dismissGuide">我知道啦</button></section>`:''}
 <section class="zone-peek"><div><span class="eyebrow">我的冒险地图</span><h2>六个诗词世界</h2></div><div class="zone-ribbon">${adventureZones.map((z,i)=>{let unlocked=zoneUnlocked(i,state.progress),pr=zoneProgress(z,state.progress);return `<a class="zone-mini ${unlocked?'':'locked'}" href="${unlocked?`#map/${z.id}`:'#map'}"><i>${z.mark}</i><b>${z.name}</b><small>${unlocked?`${pr.learned}/${pr.total} 已点亮`:'继续学习后解锁'}</small></a>`}).join('')}</div></section>
 <section class="grade-path"><article><span>一二年级</span><h2>把学过的诗找回来</h2><p>多用看图、排序和关键字回忆。</p></article><article><span>三年级</span><h2>先认识画面和声音</h2><p>建立兴趣，不提前做大量考试题。</p></article></section>`)}

function onboarding(){return shell(`<section class="narrow card newcomer"><span class="eyebrow">可跳过，不需要注册</span><h1>给小书童取个昵称</h1><p>只保存在这台设备，不要填写真实姓名。</p><label>昵称<input id="nickname" maxlength="8" placeholder="例如：小竹子"></label><div class="choice"><button data-grade="2">二年级</button><button data-grade="3" class="selected">二升三</button></div><button id="finishGuide" class="primary">开始冒险</button><button id="guestGuide">直接游客体验</button></section>`)}

function today(){ensureGuest();ensureDaily();let done=state.daily.tasks.filter(t=>t.done).length,current=state.daily.tasks.findIndex(t=>!t.done);return shell(`<section class="today-head"><div><span class="eyebrow">${esc(state.profile.nickname)}的今日路线</span><h1>${done===3?'今天的画卷修好啦':'三站小冒险'}</h1><p>一站一站走，不用一次做完。</p></div><div class="ring">${done}<small>/3</small></div></section><div class="quest-line">${state.daily.tasks.map((t,i)=>{let p=poems.find(x=>x.id===t.poemId),status=t.done?'已完成':i===current?'现在出发':'稍后开启';return `<article class="quest-stop ${t.done?'done':''} ${i===current?'current':''}"><span class="quest-no">${t.done?'✓':i+1}</span>${icon(p,i)}<div><small>${t.mode==='new'?'新诗 · 趣味预习':'旧诗 · 轻松复习'}</small><h2>${t.kind}</h2><p>《${p.title}》 · ${t.practice}</p><b>${status}</b></div><a class="button ${i===current?'primary':''}" href="#${taskStartRoute(t)}">${t.done?'再玩一次':i===current?'开始这一站':'提前看看'}</a></article>`}).join('')}</div><aside class="quest-reward"><i>卷</i><div><b>完成三站</b><span>获得诗词卡、诗人卡和 1 块主题画卷碎片</span></div></aside>`)}

function mapPage(zoneId){let learned=Object.values(state.progress).filter(p=>p.level).length,firstOpen=adventureZones.find((z,i)=>zoneUnlocked(i,state.progress)),zone=adventureZones.find(z=>z.id===zoneId)||firstOpen,zi=adventureZones.indexOf(zone),unlocked=zoneUnlocked(zi,state.progress),list=poems.filter(p=>zone.poemIds.includes(p.id));return shell(`<section class="map-head"><div><span class="eyebrow">每学一首，点亮一个地点</span><h1>我的冒险地图</h1><p>已经点亮 ${learned} 个诗词地点。</p></div><a class="button" href="#today">回到今日任务</a></section><div class="adventure-map">${adventureZones.map((z,i)=>{let open=zoneUnlocked(i,state.progress),pr=zoneProgress(z,state.progress);return `<a href="${open?`#map/${z.id}`:'#map'}" class="map-zone ${z.id===zone.id?'active':''} ${open?'':'locked'}"><i>${z.mark}</i><div><b>${z.name}</b><small>${open?pr.complete?'完整画卷已解锁':`${pr.learned}/${pr.total} 个地点`:'尚未解锁'}</small></div></a>`}).join('')}</div>${unlocked?`<section class="zone-detail"><header><div><span>${zone.mark}</span><h2>${zone.name}</h2><p>${zone.desc}</p></div><b>${zoneProgress(zone,state.progress).learned}/${zone.poemIds.length}</b></header><div class="zone-poems">${poemCards(list,true)}</div></section>`:`<section class="locked-zone">再点亮一些诗词，这片地图就会出现。</section>`}`)}
function poemCards(list,inZone=false){return list.map(p=>{let unlocked=!inZone||zoneUnlocked(adventureZones.findIndex(z=>z.poemIds.includes(p.id)),state.progress),status=poemAdventureStatus(p,state.progress,unlocked);return `<article class="poem-card adventure-card ${status.id}" data-grade="${p.grade}" data-status="${status.id}">${icon(p)}<div class="poem-card-body"><span class="status">${status.label}</span><h2>${p.title}</h2><p>${p.dynasty} · ${p.author}</p><small>${contextLabel(p)} · ${p.theme}</small>${unlocked?`<a class="button" href="#learn/${p.id}">${status.id==='review'?'去找回来':status.id==='mastered'?'再看一眼':'进入地点'} →</a>`:'<span class="locked-copy">完成前面的区域后开放</span>'}</div></article>`}).join('')}

function chooserCard(p){let level=state.progress[p.id]?.level||0;return `<article class="poem-card chooser-card" data-poem-search="${esc(`${p.title}${p.author}${p.dynasty}`)}">${icon(p)}<div class="poem-card-body"><span class="status">${masteryNames[level]||masteryNames[0]}</span><h2>${p.title}</h2><p>${p.dynasty} · ${p.author}</p><small>${p.grade} 年级${p.semester}册 · ${p.source}</small><div class="poem-mode-actions"><a href="#learn/${p.id}/full/pick">学习</a><a href="#review/${p.id}">复习</a><a href="#play/mixed/${p.id}">游戏</a><a href="#learn/${p.id}/7/pick">背诵</a></div></div></article>`}
function poemLibrary(grade='all'){let selected=[1,2,3].includes(Number(grade))?Number(grade):'all',list=selected==='all'?poems:poems.filter(p=>p.grade===selected);return shell(`<section class="map-head poem-library-head"><div><span class="eyebrow">自由选诗 · 不影响今日任务</span><h1>我想学这一首</h1><p>先选年级，再选学习、复习、游戏或背诵。</p></div><a class="button" href="#today">回到今日冒险</a></section><div class="grade-filter" role="navigation" aria-label="按年级筛选">${[['all','全部'],[1,'一年级'],[2,'二年级'],[3,'三年级']].map(([value,label])=>`<a class="${selected===value?'active':''}" href="#poems/${value}">${label}<small>${value==='all'?poems.length:poems.filter(p=>p.grade===value).length} 首</small></a>`).join('')}</div><label class="poem-search"><span>找诗名或作者</span><input id="poemSearch" type="search" placeholder="例如：静夜思、李白" autocomplete="off"></label><p id="poemResultCount" class="result-count">找到 ${list.length} 首诗</p><div id="poemChooserGrid" class="grid poem-chooser-grid">${list.map(chooserCard).join('')}</div>`) }
function reviewPoem(id){let p=poems.find(x=>x.id===id)||poems[0];return shell(`<section class="selected-poem-head"><div>${sceneVisual(p,true)}</div><div><span class="eyebrow">${p.grade} 年级${p.semester}册 · 自由复习</span><h1>《${p.title}》</h1><p>${p.dynasty} · ${p.author}</p><p>${p.childMeaning}</p><a class="button ghost" href="#poems/${p.grade}">← 换一首诗</a></div></section><section class="review-choice"><h2>这次想怎样复习？</h2><p>只练一个小目标，完成后会记录这首诗的复习情况。</p><div><a href="#learn/${p.id}/2/pick"><i>听</i><b>听读与讲解</b><span>朗读、重点词语、逐句意思</span></a><a href="#learn/${p.id}/4/pick"><i>序</i><b>诗句排序</b><span>把整首诗按画面顺序排好</span></a><a href="#learn/${p.id}/5/pick"><i>填</i><b>关键字填空</b><span>十轮提示逐渐减少</span></a><a href="#learn/${p.id}/6/pick"><i>懂</i><b>诗意理解</b><span>用一个小情境读懂画面</span></a><a href="#learn/${p.id}/7/pick"><i>背</i><b>完整背诵</b><span>文字逐渐消失，最后只看画</span></a></div></section>`) }

function secretHua(p){let found=session.learn.secrets||[];return `<h2>寻找古画中的四个秘密</h2>${role('baize','这幅画有四件不可能发生的事。点一点，把秘密找出来。')}<div class="hua-secrets">${sceneVisual(p,true)}<div class="secret-grid">${p.lines.map((line,i)=>`<button data-secret="${i}" class="secret ${found.includes(String(i))?'found':''}"><i>${i+1}</i><b>${['点远山','听流水','换季节','靠近小鸟'][i]}</b><span>${found.includes(String(i))?line:['山是什么颜色？','为什么听不到声音？','春天过去会怎样？','小鸟会飞走吗？'][i]}</span></button>`).join('')}</div></div><div id="understandFeedback" class="correction">${found.length===4?`四个秘密都找到了！<b>${p.lines.join('，')}</b>`:`已找到 ${found.length}/4 个秘密。`}</div>`}
function regularScene(p){return `<h2>点击画面，叫醒诗句</h2>${role('baize')}<div class="scene-learning"><div>${sceneVisual(p)}</div><div><div class="explain-list">${p.lines.map((line,i)=>`<button class="explain" data-understand="${i}"><i>${i+1}</i><b>${p.imagery[i]||`画面 ${i+1}`}</b><span>${(session.learn.understood||[]).includes(String(i))?`${line} · ${p.explanations[i]}`:'点开看看这幅画藏着哪句诗'}</span></button>`).join('')}</div><div id="understandFeedback" class="correction">已叫醒 ${(session.learn.understood||[]).length}/${p.lines.length} 句诗。</div></div></div>`}
function fadePoem(p,level=0){return p.lines.map((line,i)=>{let visible=level===0?line:level===1?`${line.slice(0,Math.ceil(line.length*.65))}${'＿'.repeat(Math.floor(line.length*.35))}`:level===2?`${line.slice(0,2)}${'＿'.repeat(Math.max(2,line.length-2))}`:level===3?`${line[0]}${'＿'.repeat(Math.max(3,line.length-1))}`:'只看画面，自己背';return `<p>${visible}<small>${level<4?rhythmGuide(line):`第 ${i+1} 幅画面`}</small></p>`}).join('')}
function typoHunt(blank,game=false){const attribute=game?'data-game-typo-index':'data-typo-index',text=blank.masked||blank.typoLine;return `<div class="${game?'game-typo-hunt':'typo-hunt'}" aria-label="点击找出被换错的字">${[...text].map((char,i)=>/[，。！？；、]/.test(char)?`<span>${char}</span>`:`<button ${attribute}="${i}" aria-label="第 ${i+1} 个字，${char}">${char}</button>`).join('')}</div>`}
function blankPractice(blank){const buttons=`<div class="word-bank ${blank.interaction}">${blank.options.map(x=>`<button data-fill="${esc(x)}">${x}</button>`).join('')}</div>`;if(blank.interaction==='typo-hunt')return `<section class="practice-stage typo-stage"><div class="practice-cue"><b>先想这幅画</b><span>${blank.cue}</span></div><h3>哪个字和画面意思不一样？</h3>${typoHunt(blank)}</section>`;if(blank.interaction==='whole-line')return `<section class="practice-stage whole-line-stage"><div class="recall-cue"><i>第 ${blank.lineIndex+1} 句</i><div><b>先想这幅画</b><span>${blank.cue}</span></div></div><h3>哪一句写的是这幅画？</h3>${buttons}</section>`;if(blank.interaction==='line-bridge')return `<section class="practice-stage bridge-stage"><div class="line-bridge-cue"><span>上句</span><b>${blank.before}</b><i>接住紧跟着的下一句 ↓</i></div>${buttons}</section>`;return `<section class="practice-stage ${blank.interaction}">${blank.cue?`<div class="practice-cue"><b>画面线索</b><span>${blank.cue}</span></div>`:''}<div class="fill-sentence">${blank.masked}</div>${buttons}</section>`}
function practiceHint(blank){if(blank.interaction==='typo-hunt'){let place=blank.answerIndex<blank.line.length/2?'前半句':'后半句';return `错字藏在${place}。想一想，哪个字让画面意思变了？`}if(blank.interaction==='whole-line')return `这一句从“${blank.line[0]}”开始，再对照第 ${blank.lineIndex+1} 幅画面。`;if(blank.interaction==='line-bridge')return `紧跟着的下一句从“${blank.line[0]}”开始。`;if(blank.cue)return blank.cue;return `答案有 ${blank.word.length} 个字，第一个字是“${blank.word[0]}”。`}

function learn(id,startStep,source){
 const p=poems.find(x=>x.id===id)||poems[0];
 const requestedReview=Number(startStep)||0;
 if(session.learn?.id!==id||session.learn?.context!==(source||'')||session.learn?.entry!==(startStep||'')||(requestedReview&&session.learn.reviewStep!==requestedReview)){const resume=!requestedReview&&state.resume?.poemId===id?state.resume:null;session.learn={id,entry:startStep||'',step:requestedReview||resume?.step||1,reviewOnly:Boolean(requestedReview||resume?.reviewOnly),reviewStep:requestedReview||resume?.reviewStep||0,context:source||resume?.context||'',exitRoute:source==='pick'?`review/${p.id}`:resume?.exitRoute||'today',hints:resume?.hints||0,startedAt:resume?.startedAt||Date.now(),understood:resume?.understood||[],secrets:resume?.secrets||[],blankIndex:resume?.blankIndex||0,listenClues:resume?.listenClues||[],listened:resume?.listened||false,guessPassed:resume?.guessPassed||false,orderSelected:resume?.orderSelected||[],orderPassed:resume?.orderPassed||false,fillPassed:resume?.fillPassed||false,meaningPassed:resume?.meaningPassed||false,meaningCorrect:resume?.meaningCorrect,selfRating:resume?.selfRating||null,fadeLevel:resume?.fadeLevel||0}}
 const step=session.learn.step;persistLearn();
 const childMeaning=p.childMeaning||`${p.explanations.slice(0,2).join('，')}。这首诗请我们把这些画面连起来，慢慢体会诗人的心情。`;
 let body='';
 if(step===1)body=`<h2>看图猜诗</h2><p class="mission-copy">先看画面，不公布诗名。你觉得藏着哪首诗？</p>${sceneVisual(p,true)}<div id="guessFeedback" class="correction">选一个答案，可以再试。</div><div class="choice vertical">${[p.title,...poems.filter(x=>x.id!==id).slice(0,3).map(x=>x.title)].sort().map(x=>`<button data-answer="${esc(x)}">${x}</button>`).join('')}</div>`;
 if(step===2)body=`<h2>听诗，找景物</h2>${role('scholar','先听完整首诗，再点出你听到的景物。')}<div class="listen-scene"><section class="recitation-panel"><div class="poem-lines">${p.lines.map((line,i)=>`<p data-line="${i}">${state.settings.pinyin?`<ruby>${line}<rt>${p.pinyin[i]}</rt></ruby>`:line}<small>${rhythmGuide(line)}</small><button class="speak-line" data-i="${i}" aria-label="重复播放第${i+1}句">▶</button></p>`).join('')}</div><div class="actions compact"><button id="chantPoem" class="chant-button">♫ 诗意吟诵</button><button id="speakAll" class="primary">▶ 标准朗读</button><button id="followRead">慢速跟读</button><button id="stopSpeak">暂停</button></div></section><section class="listen-side"><div class="listen-clues">${p.imagery.slice(0,4).map((x,i)=>`<button data-listen-clue="${i}"><b>${x}</b><span>${(session.learn.listenClues||[]).includes(String(i))?'听到了！':'点一下'}</span></button>`).join('')}</div><div id="listenFeedback" class="correction">已找到 ${(session.learn.listenClues||[]).length}/${Math.min(4,p.imagery.length)} 个景物。</div><section class="reading-notes compact-notes"><span class="eyebrow">儿童诗意讲解</span><div class="note-tabs" role="tablist" aria-label="朗读讲解"><button class="active" data-note-tab="meaning">诗里藏着什么</button><button data-note-tab="terms">重点词语</button><button data-note-tab="lines">逐句看懂</button></div><div data-note-panel="meaning">${role('baize','朗读完，听我把整幅画轻轻讲给你。')}<p class="meaning-summary">${childMeaning}</p><button id="speakMeaning" class="primary">▶ 听白泽先生讲一讲</button></div><div data-note-panel="terms" hidden><h3>重点词语</h3><dl class="term-grid">${(termNotes[p.id]||[]).map(([word,meaning])=>`<div><dt>${word}</dt><dd>${meaning}</dd></div>`).join('')}</dl></div><div data-note-panel="lines" hidden><h3>逐句看懂</h3><div class="line-notes">${p.lines.map((line,i)=>`<p><b>${line}</b><span>${p.explanations[i]}</span></p>`).join('')}</div></div></section></section></div>`;
 if(step===3)body=p.id==='hua'?secretHua(p):regularScene(p);
 if(step===4){let shuffled=shuffledCopy(p.lines);body=`<h2>把诗句送回家</h2>${role('ink')}<p class="mission-copy">电脑可拖动，手机点一句也能放入正确位置。</p><div class="order-layout"><div><h3>被打乱的诗句</h3><div class="choice vertical">${shuffled.map(x=>`<button draggable="true" data-order="${esc(x)}">${x}</button>`).join('')}</div></div><div><h3>完整诗卷</h3><div id="orderTarget" class="order-target"><span class="placeholder">从第一句开始</span></div><div class="actions"><button id="undoOrder">撤回</button><button id="resetOrder">重新排</button></div><div id="orderFeedback" class="correction">墨团子会马上告诉你位置对不对。</div></div></div>`}
 if(step===5){let index=session.learn.blankIndex||0,blank=blankForPoem(p,index),kinds=['句首认字','句尾补词','诗中词语','整句回忆','上下句接龙','辨认错字'];session.learn.blank=blank;body=`<div class="round-head"><div><span class="eyebrow">错字精灵的挑战</span><h2>每一轮，玩法都不同</h2></div><b>${index+1}/10</b></div>${role('typo',index<3?'先看清题目给了什么线索。':index<7?'把诗句和画面连起来想。':'最后几轮，也会给你能推理的线索。')}<div class="practice-kinds">${kinds.map(x=>`<span class="${x===blank.kind?'active':''}">${x}</span>`).join('')}</div><div class="round-track">${Array.from({length:10},(_,i)=>`<i class="${i<index?'done':i===index?'current':''}">${i+1}</i>`).join('')}</div><p class="practice-instruction"><b>${blank.kind}</b><span>${blank.instruction}</span></p>${blankPractice(blank)}<div id="fillFeedback" class="correction" aria-live="polite">${blank.interaction==='typo-hunt'?'点一下你觉得被换错的那个字。':blank.interaction==='whole-line'?'四句都在诗里，请根据“第几句”和画面来选。':blank.interaction==='line-bridge'?'先读上句，再沿着诗的顺序接下去。':'把合适的字词送回空白处。'}</div><div class="actions">${index?'<button id="prevBlank">上一轮</button>':''}<button id="hint">再给我一点线索</button></div>`}
 if(step===6){let q=meaningChallenge(p,poems.indexOf(p)+state.activities.length);session.learn.meaningQuestion=q;body=`<h2>破解诗词秘密</h2>${role('baize','不用背答案，先想自己走进画面会看到、听到或感到什么。')}<div class="meaning-quest"><p>${q.prompt}</p><div class="choice vertical">${q.options.map(x=>`<button data-meaning="${esc(x)}">${x}</button>`).join('')}</div><div id="meaningFeedback" class="correction">想一想画面的季节、声音和心情。</div></div><section class="reading-notes"><h3>再听一遍整首诗的画面</h3><p class="meaning-summary">${childMeaning}</p></section>`}
 if(step===7)body=`<h2>诗词大挑战</h2>${role('scholar','每点一次，文字就少一点。最后只看画面背诵。')}<div class="recite-challenge">${sceneVisual(p,true)}<div id="fadePoem" class="fade-poem">${fadePoem(p,session.learn.fadeLevel||0)}</div><div class="fade-controls">${[0,1,2,3,4].map(i=>`<button data-fade="${i}" class="${(session.learn.fadeLevel||0)===i?'active':''}">${['全文','少一点','首字','一字','只看图'][i]}</button>`).join('')}</div></div><div class="recorder"><button id="record" class="primary">开始录音</button><button id="playback" disabled>播放我的朗诵</button></div><p id="recordStatus" class="correction">录音只留在当前页面，不会上传。</p><div class="choice vertical self-rating"><button data-rating="independent">我只看画面也背出来了</button><button data-rating="prompted">我看了一点提示</button><button data-rating="practice">我还想再练一次</button></div>`;
 if(step===8){let reward=session.learn.reward||rewardForPoem(p),picked=session.learn.context==='pick';body=`<div class="complete adventure-complete">${role('messenger',p.id==='hua'?'四个秘密都找到了，古画已经修复完整！':'你的诗词收藏已经送到！')}<div class="restored-scroll"><img src="${sceneFiles[p.id]}" alt="修复完成的${p.title}诗意画卷"><i>完成</i></div><h2>《${p.title}》冒险完成</h2><div class="collection-earned"><span><i>卡</i><b>${reward.poemCard}</b></span><span><i>印</i><b>${reward.stamp}</b></span><span><i>卷</i><b>${reward.piece}</b></span></div><div class="actions"><a class="button primary" href="${picked?`#poems/${p.grade}`:'#today'}">${picked?'继续选诗':'回到今日路线'}</a><a class="button" href="#studio/${p.id}">给这首诗配画</a></div></div>`}
 const sectionNames=['猜诗','听景','找秘密','排序','填字','理解','背诵','奖励'],mystery=step===1,reviewOnly=session.learn.reviewOnly;
 const stepper=reviewOnly?`<div class="quest-stepper review-stepper"><i class="active">复<small>${sectionNames[step-1]}</small></i></div>`:`<div class="quest-stepper">${sectionNames.map((x,i)=>`<i class="${i+1===step?'active':i+1<step?'done':''}">${i+1}<small>${x}</small></i>`).join('')}</div>`;
 return shell(`<div class="learn-top"><a href="#${session.learn.context==='pick'?`review/${p.id}`:'today'}">← 暂时离开</a><div class="bar"><i style="width:${reviewOnly?100:step/8*100}%"></i></div><b>${reviewOnly?'专项复习':`${step}/8`}</b></div><article class="learning card step-${step}"><section class="poem-learning-head ${mystery?'mystery':''}"><div><span>${mystery?'神秘诗词任务':reviewOnly?'今天的记忆复习':'正在冒险'}</span><h1>${mystery?'一首藏在画里的诗':`《${p.title}》`}</h1>${mystery?'':`<p>${p.dynasty} · ${p.author}</p>`}</div>${mystery?'':`<button id="speakTitle">▶ 听诗名</button>`}</section>${stepper}<div class="lesson-body"><span class="eyebrow">${reviewOnly?'今天只练这一项':`第 ${step} 关`}</span>${body}</div>${step<8?`<div class="step-actions"><button id="learnNext" class="primary">${reviewOnly?'完成这次复习':step===5&&(session.learn.blankIndex||0)<9?'下一轮':step===7?'领取奖励':'继续下一关'}</button></div>`:''}</article>`)
}

function games(){return shell(`<section class="game-hero"><div><span class="eyebrow">每局约 5 分钟</span><h1>今天想玩哪一种？</h1><p>玩法会轮换，答错后先给提示，再给一次机会。</p></div><div class="reward-mini"><b>墨团子今日出题</b><span>不设排行榜，和昨天的自己比</span></div></section><div class="grid games">${gameModes.map((d,i)=>`<article class="game-card ${i===0?'featured':''}"><span class="game-symbol">${d.icon}</span><small>${i===0?'今日推荐':'8 题 · 会自动纠错'}</small><h2>${d.title}</h2><p>${d.desc}</p><a class="button primary" href="#play/${d.id}">开始 →</a></article>`).join('')}</div>`)}
function ensureGame(type,poemId){let key=`${type}:${poemId||'all'}`;if(session.game?.key!==key){if(state.activeGame?.key===key)session.game=state.activeGame;else{let eligible=poems.filter(p=>p.grade<=(state.profile?.grade||3)),target=poems.find(p=>p.id===poemId),seed=state.activities.length%eligible.length;session.game={key,type,poemId:target?.id||null,questions:target?createPoemGameRound(type,target,eligible,8,seed):createGameRound(type,eligible,8,seed),index:0,score:0,points:0,wrong:[],answered:false,review:false,startedAt:Date.now(),activeSeconds:0,lastActiveAt:Date.now(),attempts:0};state.activeGame=session.game;save()}}}
function play(type,poemId){ensureGuest();ensureGame(type,poemId);let g=session.game;if(g.index>=g.questions.length)return gameResult();let q=g.questions[g.index],p=poems.find(x=>x.id===q.poemId),interaction;if(q.type==='order'||q.type==='puzzle')interaction=`<div id="gameOrderTarget" class="order-target"><span class="placeholder">从第一句开始</span></div><div class="choice vertical">${q.options.map(x=>`<button data-game-order="${esc(x)}">${x}</button>`).join('')}</div><div class="actions"><button id="gameOrderUndo">撤回</button><button id="gameOrderReset">重排</button></div>`;else if(q.interaction==='typo-hunt')interaction=`<div class="practice-cue"><b>先想诗句的画面</b><span>${q.tip}</span></div>${typoHunt(q,true)}`;else if(q.visual)interaction=`<div class="visual-options">${q.options.map(pid=>{let op=poems.find(x=>x.id===pid);return `<button data-game-answer="${pid}" data-correct="${pid===q.answer}">${icon(op)}<b>选择这幅画</b></button>`}).join('')}</div>`;else interaction=`<div class="choice ${q.type==='blank'?'word-bank '+q.interaction:'vertical'}">${q.options.map(x=>`<button data-game-answer="${esc(x)}" data-correct="${x===q.answer}">${x}</button>`).join('')}</div>`;return shell(`<section class="narrow card game-play"><div class="game-status"><span>${g.poemId?`《${p.title}》专属游戏`:g.review?'回来纠正':'随机玩法'}</span><b>${g.index+1}/${g.questions.length}</b><span id="gameTimer">${q.timed?'12 秒':'诗叶 +'+g.points}</span></div><div class="bar"><i style="width:${g.index/g.questions.length*100}%"></i></div>${q.visual?'':icon(p)}<span class="eyebrow">${gameModes.find(x=>x.id===q.type)?.title||'小挑战'}</span><h1>${q.prompt}</h1>${interaction}<p id="gameFeedback" class="correction" aria-live="polite">${q.interaction==='typo-hunt'?'直接点一下被换错的字。':q.type==='order'||q.type==='puzzle'?'点一句就会马上告诉你对不对。':''}</p><div id="gameActions" class="actions end"></div><a class="button ghost" href="${g.poemId?`#review/${g.poemId}`:'#games'}">暂时离开</a></section>`)}
function gameResult(){let g=session.game,accuracy=Math.round(g.score/Math.max(1,g.questions.length)*100),p=g.poemId?poems.find(x=>x.id===g.poemId):null;return shell(`<section class="narrow card complete game-result">${role('ink',g.wrong.length?'被你抓住了几个容易忘的地方，下次我还会来考你。':'这次完全没难住你！')}<h1>${p?`《${p.title}》练得更牢了`:accuracy>=80?'诗句接得真稳':'想起来一次，就更牢一点'}</h1><div class="summary"><span>答对率<b>${accuracy}%</b></span><span>纠正题<b>${g.wrong.length}</b></span></div><div class="actions"><button id="playAgain" class="primary">换一组题</button><a class="button" href="${p?`#review/${p.id}`:'#games'}">${p?'回到这首诗':'换个玩法'}</a></div></section>`)}

function tree(){let c=state.collections||{},learned=Object.values(state.progress).filter(p=>p.level).length;return shell(`<section class="collection-head"><div><span class="eyebrow">没有排名，只有自己的收藏</span><h1>我的诗词宝库</h1><p>已点亮 ${learned} 个地点，收集 ${c.poemCards?.length||0} 张诗词卡。</p></div><a class="button primary" href="#map">继续点亮地图</a></section><div class="collection-grid"><article><i>卡</i><h2>诗词卡片</h2><div>${(c.poemCards||[]).map(x=>`<span>${x}</span>`).join('')||'<p>完成一首诗，就会收到第一张卡。</p>'}</div></article><article><i>人</i><h2>诗人卡片</h2><div>${(c.poetCards||[]).map(x=>`<span>${x}</span>`).join('')||'<p>诗仙信使还在路上。</p>'}</div></article><article><i>印</i><h2>朝代印章</h2><div>${(c.stamps||[]).map(x=>`<span>${x}</span>`).join('')||'<p>认识诗词后盖上年代印章。</p>'}</div></article><article><i>卷</i><h2>山水画卷碎片</h2><div>${(c.pieces||[]).map(x=>`<span>${x}</span>`).join('')||'<p>完成主题区域可以拼成完整画卷。</p>'}</div></article></div>`)}

function studio(id){let p=poems.find(x=>x.id===id)||poems[0];return shell(`<section class="studio-head"><div><span class="eyebrow">孩子的作品不会上传</span><h1>我的诗配画小屋</h1><p>选颜色、选心情，再给诗人留一句话。</p></div></section><div class="studio-layout"><section class="studio-canvas palette-jade"><img id="studioImage" src="${sceneFiles[p.id]}" alt="${p.title}诗配画"><div><b>《${p.title}》</b><span>${p.dynasty} · ${p.author}</span><p id="studioNote">我在这首诗里看见了……</p></div></section><section class="studio-tools card"><label>选择诗词<select id="studioPoem">${poems.map(x=>`<option value="${x.id}" ${x.id===p.id?'selected':''}>${x.title}</option>`).join('')}</select></label><fieldset><legend>给画面配颜色</legend><button data-palette="jade">青绿色</button><button data-palette="warm">暖橙色</button><button data-palette="moon">月夜蓝</button></fieldset><fieldset><legend>这首诗像什么心情？</legend>${['开心','安静','想念','惊喜'].map(x=>`<button data-studio-mood="${x}">${x}</button>`).join('')}</fieldset><label>给诗人写一句话<textarea id="studioText" maxlength="60" placeholder="例如：李白，我也喜欢抬头看月亮。"></textarea></label><div class="actions"><button id="saveCreation" class="primary">保存作品卡</button><button id="printCreation">打印作品</button></div><p id="studioFeedback" class="correction"></p></section></div>`)}

function parent(){if(!state.parentUnlocked)return shell(`<section class="narrow card parent-lock"><h1>家长入口</h1><p>成人验证：27 + 16 = ?</p><input id="parentAnswer" inputmode="numeric" aria-label="答案"><button id="unlockParent" class="primary">查看学习报告</button><p id="parentError"></p></section>`);let weekAgo=Date.now()-7*86400000,acts=state.activities.filter(a=>new Date(a.date).getTime()>=weekAgo),learned=new Set(acts.filter(a=>a.type==='learning').map(a=>a.poemId)),independent=new Set(acts.filter(a=>a.selfRating==='independent').map(a=>a.poemId)),prompted=new Set(acts.filter(a=>a.selfRating==='prompted'||a.selfRating==='practice').map(a=>a.poemId)),notUnderstood=new Set(acts.filter(a=>a.understanding===false).map(a=>a.poemId)),minutes=Math.round(acts.reduce((n,a)=>n+(a.seconds||0),0)/60),days=new Set(acts.map(a=>a.date.slice(0,10))).size,errors=Object.entries(state.progress).filter(([,p])=>p.errors?.length).slice(0,5);return shell(`<section class="parent-report"><header><div><span class="eyebrow">近 7 天</span><h1>家长行动报告</h1></div><a class="button" href="#home">回到孩子首页</a></header><div class="parent-metrics"><span><b>${learned.size}</b>学习诗词</span><span><b>${independent.size}</b>独立背诵</span><span><b>${prompted.size}</b>仍需提示</span><span><b>${minutes}</b>有效分钟</span><span><b>${days}</b>学习天数</span></div><article class="parent-advice"><h2>下周直接这样做</h2><p>${parentAdvice(poems,state.progress)}</p></article><div class="parent-grid"><article class="card"><h2>还需提示</h2>${[...prompted].map(id=>`<p>《${poems.find(p=>p.id===id)?.title}》</p>`).join('')||'<p>暂未记录。</p>'}</article><article class="card"><h2>只会背，还没完全听懂</h2>${[...notUnderstood].map(id=>`<p>《${poems.find(p=>p.id===id)?.title}》</p>`).join('')||'<p>暂未发现。</p>'}</article><article class="card"><h2>被偷走的诗句</h2>${errors.map(([id,p])=>`<p><b>《${poems.find(x=>x.id===id)?.title}》</b><span>${[...new Set(p.errors)].slice(-2).join('、')}</span></p>`).join('')||'<p>暂时没有集中错点。</p>'}</article><article class="card"><h2>下一次复习</h2>${Object.entries(state.progress).filter(([,p])=>p.nextReviewAt).sort((a,b)=>a[1].nextReviewAt-b[1].nextReviewAt).slice(0,5).map(([id,p])=>`<p>《${poems.find(x=>x.id===id)?.title}》 · ${new Date(p.nextReviewAt).toLocaleDateString('zh-CN')}</p>`).join('')||'<p>完成第一首诗后出现。</p>'}</article></div></section>`)}
function settings(){let s=state.settings;return shell(`<section class="narrow card form"><h1>舒服地学习</h1><label><span>静音模式</span><input id="sound" type="checkbox" ${!s.sound?'checked':''}></label><label><span>轻柔背景音乐</span><input id="music" type="checkbox" ${s.music?'checked':''}></label><label><span>显示拼音</span><input id="pinyin" type="checkbox" ${s.pinyin?'checked':''}></label><label><span>护眼模式</span><input id="eyeCare" type="checkbox" ${s.eyeCare?'checked':''}></label><label><span>减少动画</span><input id="reduceMotion" type="checkbox" ${s.reduceMotion?'checked':''}></label><label><span>字体</span><select id="font"><option value="normal">大字</option><option value="large" ${s.font==='large'?'selected':''}>更大字</option></select></label><button id="saveSettings" class="primary">保存设置</button><button id="clearData" class="danger">清空这台设备的记录</button></section>`)}

let gameTimerId=null;
function render(){if(gameTimerId){clearInterval(gameTimerId);gameTimerId=null}let [page,id,startStep,context]=route.split('/'),views={home,onboarding,today,poems:()=>poemLibrary(id),review:()=>reviewPoem(id),map:()=>mapPage(id),learn:()=>learn(id,startStep,context),games,play:()=>play(id,startStep),tree,studio:()=>studio(id),parent,settings};document.body.classList.toggle('focus-mode',page==='learn'||page==='play');$('#app').innerHTML=(views[page]||home)();bind(page,id)}
function persistLearn(){if(!session.learn)return;state.resume={poemId:session.learn.id,entry:session.learn.entry,step:session.learn.step,reviewOnly:session.learn.reviewOnly,reviewStep:session.learn.reviewStep,context:session.learn.context,exitRoute:session.learn.exitRoute,hints:session.learn.hints,startedAt:session.learn.startedAt,understood:session.learn.understood,secrets:session.learn.secrets,blankIndex:session.learn.blankIndex,listenClues:session.learn.listenClues||[],listened:session.learn.listened||false,guessPassed:session.learn.guessPassed||false,orderSelected:session.learn.orderSelected||[],orderPassed:session.learn.orderPassed||false,fillPassed:session.learn.fillPassed||false,meaningPassed:session.learn.meaningPassed||false,meaningCorrect:session.learn.meaningCorrect,selfRating:session.learn.selfRating||null,fadeLevel:session.learn.fadeLevel||0,updatedAt:Date.now()};save()}
function finishLearning(id){let p=poems.find(x=>x.id===id),old=state.progress[id]||{},rating=session.learn.selfRating,correct=rating!=='practice'&&session.learn.meaningCorrect!==false,error=rating==='practice'?'背诵需要提示':session.learn.meaningCorrect===false?'诗意理解':session.learn.hints>2?'关键字回忆':null;state.progress[id]=scheduleReview(old,{correct,hints:session.learn.hints,recitation:true,selfRating:rating,errorType:error});let seconds=Math.max(20,Math.round((Date.now()-session.learn.startedAt)/1000)),first=!state.activities.some(a=>a.type==='learning'&&a.poemId===id);state.activities.push({date:new Date().toISOString(),poemId:id,type:'learning',score:rating==='independent'?100:rating==='prompted'?75:55,seconds,selfRating:rating,understanding:session.learn.meaningCorrect!==false});state.rewards.points=(state.rewards.points||0)+(first?30:5);state.rewards.poemsCompleted=(state.rewards.poemsCompleted||0)+(first?1:0);state.rewards.minutesLearned=(state.rewards.minutesLearned||0)+Math.round(seconds/60);session.learn.reward=addPoemReward(state,p);ensureDaily();let task=state.daily.tasks.find(t=>t.poemId===id&&!t.done);if(task)task.done=true;state.resume=null;save()}
function finishReview(id){const old=state.progress[id]||{},step=session.learn.reviewStep||session.learn.step,rating=session.learn.selfRating,practiceType=step===4?'诗句顺序':step===5?'关键字回忆':step===6?'诗意理解':step===7?'背诵需要提示':'看图回忆',correct=session.learn.meaningCorrect!==false&&rating!=='practice',error=correct?null:practiceType;let next=scheduleReview(old,{correct,hints:session.learn.hints,recitation:step===7,selfRating:rating,errorType:error,practiceType});if(correct&&step!==7)next.level=Math.max(old.level||0,next.level||0);state.progress[id]=next;state.activities.push({date:new Date().toISOString(),poemId:id,type:'review',score:correct?100:70,seconds:Math.max(15,Math.round((Date.now()-session.learn.startedAt)/1000)),correct,errorType:error});state.rewards.points=(state.rewards.points||0)+5;let task=state.daily?.tasks?.find(t=>t.mode==='review'&&t.poemId===id&&!t.done);if(task)task.done=true;state.resume=null;save()}
function setOrderUI(selected,target,selector){target.innerHTML=selected.length?selected.map((x,i)=>`<span><b>${i+1}</b>${x}</span>`).join(''):'<span class="placeholder">从第一句开始</span>';document.querySelectorAll(selector).forEach(b=>b.disabled=selected.includes(b.dataset.order||b.dataset.gameOrder))}
function recordGameAnswer(type,ok){let g=session.game,q=g.questions[g.index],p=poems.find(x=>x.id===q.poemId);g.answered=true;if(ok){g.score++;g.points+=pointsForAnswer(true,g.attempts?2:1)}else if(!g.review)g.wrong.push(q);let names={order:'诗句顺序',puzzle:'诗句顺序',blank:'关键字回忆',next:'上下句衔接',typo:'易错字',title:'诗名识别',author:'作者记忆',poet:'作者记忆',season:'季节理解',theme:'诗意理解',emotion:'诗意理解',same:'相似句混淆',identity:'诗名作者',scene:'画面理解',timed:'景物识别'},practiceType=names[q.type];state.activities.push({date:new Date().toISOString(),poemId:p.id,type:`game-${type}`,score:ok&&g.attempts===0?100:ok?80:60,correct:ok&&g.attempts===0,errorType:g.attempts?practiceType:null});state.progress[p.id]=scheduleReview(state.progress[p.id],{correct:ok&&g.attempts===0,hints:g.attempts||0,errorType:g.attempts?practiceType:null,practiceType});save()}
function showGameNext(type){let g=session.game;$('#gameActions').innerHTML='<button id="nextGame" class="primary">下一题</button>';$('#nextGame').onclick=()=>{g.index++;g.answered=false;g.attempts=0;if(g.index===g.questions.length&&g.wrong.length&&!g.review){g.questions=[...g.questions,...g.wrong];g.review=true}if(g.index>=g.questions.length){state.rewards.points=(state.rewards.points||0)+g.points+(g.wrong.length?10:20);state.rewards.gamesCompleted=(state.rewards.gamesCompleted||0)+1;state.activeGame=null}else state.activeGame=g;save();render();scrollTo(0,0)}}

let ambient=null,speechSequence=0,chineseVoice=null;
function startMusic(){if(!state.settings.music||ambient)return;try{const AudioEngine=window.AudioContext||window.webkitAudioContext,ctx=new AudioEngine(),master=ctx.createGain(),notes=[174.61,196,220,261.63,293.66,261.63,220,196];let index=0;master.gain.value=.018;master.connect(ctx.destination);const pluck=()=>{if(ctx.state==='closed')return;let osc=ctx.createOscillator(),gain=ctx.createGain(),now=ctx.currentTime;osc.type='triangle';osc.frequency.value=notes[index++%notes.length];gain.gain.setValueAtTime(.0001,now);gain.gain.exponentialRampToValueAtTime(.08,now+.03);gain.gain.exponentialRampToValueAtTime(.0001,now+1.45);osc.connect(gain).connect(master);osc.start(now);osc.stop(now+1.5)};pluck();ambient={ctx,timer:setInterval(pluck,1900)}}catch{}}
function stopMusic(){if(ambient){clearInterval(ambient.timer);ambient.ctx.close();ambient=null}}
function clearSpeaking(){document.querySelectorAll('.speaking').forEach(x=>x.classList.remove('speaking'))}
function preferredChineseVoice(){if(chineseVoice)return chineseVoice;let voices=speechSynthesis.getVoices(),score=v=>{let lang=(v.lang||'').toLowerCase(),name=(v.name||'').toLowerCase(),points=lang==='zh-cn'?70:lang.startsWith('zh')?55:0;if(points&&/xiaoxiao|tingting|sinji|hiumaan|meijia|premium|enhanced|natural|neural/.test(name))points+=28;if(points&&/microsoft|apple/.test(name))points+=8;if(points&&v.localService)points+=5;return points};chineseVoice=[...voices].filter(v=>score(v)>0).sort((a,b)=>score(b)-score(a))[0]||null;return chineseVoice}
function speak(text,rate=.78,onend,el,pitch=.98){if(!state.settings.sound){if($('#listenFeedback'))$('#listenFeedback').textContent='现在是静音模式，可以在设置里打开声音。';return}if(!('speechSynthesis'in window))return;speechSynthesis.cancel();stopMusic();clearSpeaking();if(el)el.classList.add('speaking');let u=new SpeechSynthesisUtterance(text),voice=preferredChineseVoice();u.lang='zh-CN';u.rate=rate;u.pitch=pitch;u.volume=.96;if(voice)u.voice=voice;u.onend=()=>{clearSpeaking();if(state.settings.music)startMusic();onend?.()};speechSynthesis.speak(u)}
function speakPoem(p,mode='standard'){if(!('speechSynthesis'in window))return;const styles={standard:{rate:.76,delay:420,pitches:[1,.99,.98,.96]},follow:{rate:.58,delay:1200,pitches:[1,1,.99,.98]},chant:{rate:.64,delay:780,pitches:[1.04,1.01,.98,.94]}},style=styles[mode]||styles.standard,run=++speechSequence;speechSynthesis.cancel();let i=-1;const next=()=>{if(run!==speechSequence)return;if(i>=p.lines.length){session.learn.listened=true;persistLearn();return}const title=i<0,el=title?null:document.querySelector(`[data-line="${i}"]`),text=title?`${p.title}。${p.dynasty}，${p.author}`:mode==='chant'?rhythmGuide(p.lines[i]).replace(/ \/ /g,'，'):p.lines[i],rate=title?Math.min(style.rate,.7):style.rate,pitch=title ? .98 : style.pitches[i%style.pitches.length];speak(text,rate,()=>{if(run!==speechSequence)return;i++;setTimeout(next,style.delay)},el,pitch)};next()}
function setupRecorder(){if(!$('#record'))return;let rec,chunks=[],url;$('#record').onclick=async()=>{if(!navigator.mediaDevices?.getUserMedia){$('#recordStatus').textContent='当前浏览器不能录音，可以直接完成背诵自评。';return}try{let stream=await navigator.mediaDevices.getUserMedia({audio:true});rec=new MediaRecorder(stream);rec.ondataavailable=e=>chunks.push(e.data);rec.onstop=()=>{url=URL.createObjectURL(new Blob(chunks));$('#playback').disabled=false;stream.getTracks().forEach(t=>t.stop())};rec.start();$('#recordStatus').textContent='正在录音，背完后点停止。';$('#record').textContent='停止录音';$('#record').onclick=()=>{rec.stop();$('#record').textContent='已经录好'}}catch{$('#recordStatus').textContent='没有麦克风权限，没关系，可以直接自评。'}};$('#playback').onclick=()=>{speechSynthesis.cancel();url&&new Audio(url).play()}}

function bind(page,id){
 if(page==='home'){if($('#startAdventure'))$('#startAdventure').onclick=ensureGuest;if($('#dismissGuide'))$('#dismissGuide').onclick=()=>{state.guideSeen=true;save();render()}}
 if(page==='poems'&&$('#poemSearch'))$('#poemSearch').oninput=()=>{let query=$('#poemSearch').value.trim().toLowerCase(),visible=0;document.querySelectorAll('[data-poem-search]').forEach(card=>{let match=!query||card.dataset.poemSearch.toLowerCase().includes(query);card.hidden=!match;if(match)visible++});$('#poemResultCount').textContent=`找到 ${visible} 首诗`}
 if(page==='onboarding'){document.querySelectorAll('[data-grade]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-grade]').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');session.grade=+b.dataset.grade});$('#finishGuide').onclick=()=>{state.profile={nickname:$('#nickname').value.trim()||'小书童',grade:session.grade||3,goal:'复习一二年级 + 趣味预习三年级'};state.guideSeen=true;save();go('today')};$('#guestGuide').onclick=()=>{ensureGuest();go('today')}}
 if(page==='learn')bindLearn(poems.find(p=>p.id===id));
 if(page==='play')bindGame(id);
 if(page==='tree'&&state.settings.music)startMusic();
 if(page==='studio')bindStudio();
 if(page==='parent'&&!state.parentUnlocked)$('#unlockParent').onclick=()=>{if($('#parentAnswer').value.trim()==='43'){state.parentUnlocked=true;save();render()}else $('#parentError').textContent='再算一次，还差一点。'};
 if(page==='settings'){$('#saveSettings').onclick=()=>{state.settings.sound=!$('#sound').checked;state.settings.music=$('#music').checked;state.settings.pinyin=$('#pinyin').checked;state.settings.eyeCare=$('#eyeCare').checked;state.settings.reduceMotion=$('#reduceMotion').checked;state.settings.font=$('#font').value;state.daily=null;save();state.settings.music?startMusic():stopMusic();go('home')};$('#clearData').onclick=()=>{if(confirm('只会清空这台设备里的学习记录，确定吗？')){storage.clear();state=storage.load();go('home')}}}
}
function bindLearn(p){let selected=[...(session.learn.orderSelected||[])];
 document.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{let ok=b.dataset.answer===p.title;b.classList.add(ok?'correct':'gentle');if(ok){session.learn.guessPassed=true;$('#guessFeedback').textContent='猜对啦！诗名和作者将在下一关出现。'}else{session.learn.hints++;$('#guessFeedback').textContent=`再看看画里的“${p.imagery.slice(0,2).join('、')}”。`};persistLearn()});
 document.querySelectorAll('[data-listen-clue]').forEach(b=>b.onclick=()=>{session.learn.listenClues=session.learn.listenClues||[];if(!session.learn.listenClues.includes(b.dataset.listenClue))session.learn.listenClues.push(b.dataset.listenClue);b.classList.add('correct');b.querySelector('span').textContent='听到了！';$('#listenFeedback').textContent=`已找到 ${session.learn.listenClues.length}/${Math.min(4,p.imagery.length)} 个景物。`;persistLearn()});
 if($('#speakTitle'))$('#speakTitle').onclick=()=>{speechSequence++;speak(`${p.title}。${p.dynasty}，${p.author}`,.7)};document.querySelectorAll('.speak-line').forEach(b=>b.onclick=()=>{speechSequence++;speak(p.lines[+b.dataset.i],.7,null,b.closest('p'),.98)});if($('#chantPoem'))$('#chantPoem').onclick=()=>{session.learn.listened=true;persistLearn();if($('#listenFeedback'))$('#listenFeedback').textContent='正在诗意吟诵：听一听每句的停顿和收音。';speakPoem(p,'chant')};if($('#speakAll'))$('#speakAll').onclick=()=>{session.learn.listened=true;persistLearn();speakPoem(p,'standard')};if($('#followRead'))$('#followRead').onclick=()=>{session.learn.listened=true;persistLearn();speakPoem(p,'follow')};if($('#speakMeaning'))$('#speakMeaning').onclick=()=>{speechSequence++;speak(`${p.title}。${p.childMeaning||p.explanations.join('。')}`,.7)};if($('#stopSpeak'))$('#stopSpeak').onclick=()=>{speechSequence++;speechSynthesis.cancel();stopMusic();clearSpeaking()};
 document.querySelectorAll('[data-note-tab]').forEach(button=>button.onclick=()=>{document.querySelectorAll('[data-note-tab]').forEach(x=>x.classList.toggle('active',x===button));document.querySelectorAll('[data-note-panel]').forEach(panel=>panel.hidden=panel.dataset.notePanel!==button.dataset.noteTab)});
 document.querySelectorAll('[data-understand]').forEach(b=>b.onclick=()=>{if(!session.learn.understood.includes(b.dataset.understand))session.learn.understood.push(b.dataset.understand);b.classList.add('selected');b.querySelector('span').textContent=`${p.lines[+b.dataset.understand]} · ${p.explanations[+b.dataset.understand]}`;$('#understandFeedback').textContent=`已叫醒 ${session.learn.understood.length}/${p.lines.length} 句诗。`;persistLearn()});
 document.querySelectorAll('[data-secret]').forEach(b=>b.onclick=()=>{session.learn.secrets=session.learn.secrets||[];if(!session.learn.secrets.includes(b.dataset.secret))session.learn.secrets.push(b.dataset.secret);b.classList.add('found');b.querySelector('span').textContent=p.lines[+b.dataset.secret];$('#understandFeedback').innerHTML=session.learn.secrets.length===4?`四个秘密都找到了！<b>${p.lines.join('，')}</b>`:`已找到 ${session.learn.secrets.length}/4 个秘密。`;persistLearn()});
 const chooseOrder=b=>{const expected=p.lines[selected.length];if(b.dataset.order!==expected){session.learn.hints++;b.classList.add('gentle');$('#orderFeedback').innerHTML=`这里先放“<b>${esc(expected)}</b>”。把画面接起来再试。`;persistLearn();setTimeout(()=>b.classList.remove('gentle'),650);return}selected.push(b.dataset.order);session.learn.orderSelected=[...selected];b.classList.add('correct');setOrderUI(selected,$('#orderTarget'),'[data-order]');session.learn.orderPassed=selected.length===p.lines.length;$('#orderFeedback').textContent=session.learn.orderPassed?'顺序全对，诗卷修好啦！':`第 ${selected.length} 句到位。`;persistLearn()};
 document.querySelectorAll('[data-order]').forEach(b=>{b.onclick=()=>chooseOrder(b);b.ondragstart=e=>e.dataTransfer.setData('text/plain',b.dataset.order)});if($('#orderTarget')){setOrderUI(selected,$('#orderTarget'),'[data-order]');$('#orderTarget').ondragover=e=>e.preventDefault();$('#orderTarget').ondrop=e=>{e.preventDefault();let b=[...document.querySelectorAll('[data-order]')].find(x=>x.dataset.order===e.dataTransfer.getData('text/plain'));if(b)chooseOrder(b)}}if($('#undoOrder'))$('#undoOrder').onclick=()=>{selected.pop();session.learn.orderSelected=[...selected];session.learn.orderPassed=false;setOrderUI(selected,$('#orderTarget'),'[data-order]');persistLearn()};if($('#resetOrder'))$('#resetOrder').onclick=()=>{selected=[];session.learn.orderSelected=[];session.learn.orderPassed=false;setOrderUI(selected,$('#orderTarget'),'[data-order]');persistLearn()};
 document.querySelectorAll('[data-typo-index]').forEach(b=>b.onclick=()=>{if(b.disabled||session.learn.fillPassed)return;let blank=session.learn.blank,ok=+b.dataset.typoIndex===blank.answerIndex;if(ok){session.learn.fillPassed=true;b.classList.add('correct','repaired');b.setAttribute('aria-label',`找到了，${blank.wrongChar}应改成${blank.correctChar}`);b.innerHTML=`<del>${esc(blank.wrongChar)}</del><ins>${esc(blank.correctChar)}</ins>`;document.querySelectorAll('[data-typo-index]').forEach(x=>x.disabled=true);$('#fillFeedback').innerHTML=`找到了！“<b>${esc(blank.wrongChar)}</b>”让画面意思变了，这里应该是“<b>${esc(blank.correctChar)}</b>”。完整诗句：<b>${esc(blank.line)}</b>`}else{session.learn.hints++;b.disabled=true;b.classList.add('gentle');$('#fillFeedback').textContent='这个字没有被换走。再找找哪个字让画面意思变了。'}persistLearn()});
 document.querySelectorAll('[data-fill]').forEach(b=>b.onclick=()=>{if(b.disabled)return;let blank=session.learn.blank,ok=b.dataset.fill===blank.word;document.querySelectorAll('[data-fill]').forEach(x=>x.classList.remove('correct','gentle'));b.classList.add(ok?'correct':'gentle');if(ok){session.learn.fillPassed=true;document.querySelectorAll('[data-fill]').forEach(x=>x.disabled=true);$('#fillFeedback').innerHTML=`找回来了：<b>${esc(blank.line)}</b>`}else{session.learn.hints++;b.disabled=true;$('#fillFeedback').textContent=blank.interaction==='whole-line'?`这句也在诗里，但不是第 ${blank.lineIndex+1} 幅画面对应的句子。`:blank.interaction==='line-bridge'?'这句没有紧跟在上句后面。把全诗从上句往下接。':'这个字词放进空白处读不通，再试一次。'}persistLearn()});if($('#prevBlank'))$('#prevBlank').onclick=()=>{session.learn.blankIndex=Math.max(0,session.learn.blankIndex-1);session.learn.fillPassed=false;render();scrollTo(0,0)};if($('#hint'))$('#hint').onclick=()=>{session.learn.hints++;$('#fillFeedback').textContent=practiceHint(session.learn.blank)};
 document.querySelectorAll('[data-meaning]').forEach(b=>b.onclick=()=>{let ok=b.dataset.meaning===session.learn.meaningQuestion.answer;b.classList.add(ok?'correct':'gentle');if(ok){session.learn.meaningPassed=true;session.learn.meaningCorrect=session.learn.meaningCorrect!==false;$('#meaningFeedback').textContent='你读懂了画面！'}else{session.learn.hints++;session.learn.meaningCorrect=false;$('#meaningFeedback').textContent=`白泽先生提示：${p.explanations[0]}。再选一次。`}persistLearn()});
 document.querySelectorAll('[data-fade]').forEach(b=>b.onclick=()=>{session.learn.fadeLevel=+b.dataset.fade;$('#fadePoem').innerHTML=fadePoem(p,session.learn.fadeLevel);document.querySelectorAll('[data-fade]').forEach(x=>x.classList.toggle('active',x===b));persistLearn()});document.querySelectorAll('[data-rating]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-rating]').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');session.learn.selfRating=b.dataset.rating;$('#recordStatus').textContent=b.dataset.rating==='independent'?'已记录：以后会在更少提示下再见。':b.dataset.rating==='prompted'?'已记录：下次先看画面回忆。':'没关系，明天会安排更短的练习。';persistLearn()});setupRecorder();
 if($('#learnNext'))$('#learnNext').onclick=()=>{let s=session.learn.step,feedback=id=>$(id);if(s===1&&!session.learn.guessPassed){feedback('#guessFeedback').textContent='先猜对诗名，再打开下一关。';return}if(s===2&&(!session.learn.listened||(session.learn.listenClues||[]).length<Math.min(4,p.imagery.length))){feedback('#listenFeedback').textContent='先听完整首诗，并找到四个景物。';return}if(s===3&&((p.id==='hua'?(session.learn.secrets||[]):session.learn.understood).length<p.lines.length)){feedback('#understandFeedback').textContent='还差一个画面秘密没有找到。';return}if(s===4&&!session.learn.orderPassed){feedback('#orderFeedback').textContent='先把全部诗句送回正确位置。';return}if(s===5&&!session.learn.fillPassed){feedback('#fillFeedback').textContent=`先完成这一轮“${session.learn.blank.kind}”。`;return}if(s===6&&!session.learn.meaningPassed){feedback('#meaningFeedback').textContent='先完成这道画面情境题。';return}if(s===7&&!session.learn.selfRating){feedback('#recordStatus').textContent='背一遍，再选择最符合的完成情况。';return}if(session.learn.reviewOnly){let exit=session.learn.exitRoute||'today';finishReview(p.id);session.learn=null;go(exit);return}if(s===5&&session.learn.blankIndex<9){session.learn.blankIndex++;session.learn.fillPassed=false;persistLearn();render();scrollTo(0,0);return}if(s===7)finishLearning(p.id);session.learn.step++;session.learn.orderSelected=[];session.learn.orderPassed=false;session.learn.fillPassed=false;if(session.learn.step<8)persistLearn();render();scrollTo(0,0)}
}
function bindGame(type){let g=session.game;if(g.index>=g.questions.length){$('#playAgain').onclick=()=>{session.game=null;state.activeGame=null;save();render()};return}let q=g.questions[g.index];if(q.timed){let seconds=12;gameTimerId=setInterval(()=>{seconds--;if($('#gameTimer'))$('#gameTimer').textContent=`${seconds} 秒`;if(seconds<=0){clearInterval(gameTimerId);gameTimerId=null;if(!g.answered){g.attempts=1;$('#gameFeedback').textContent=`时间到啦。${q.tip} 现在慢慢选也可以。`}}},1000)}document.querySelectorAll('[data-game-typo-index]').forEach(b=>b.onclick=()=>{if(g.answered||b.disabled)return;let ok=+b.dataset.gameTypoIndex===q.answerIndex;if(!ok&&!g.attempts){g.attempts=1;b.disabled=true;b.classList.add('gentle');$('#gameFeedback').textContent='这个字没有被换走。再看看哪个字让画面意思变了。';save();return}let buttons=[...document.querySelectorAll('[data-game-typo-index]')],answerButton=buttons.find(x=>+x.dataset.gameTypoIndex===q.answerIndex);buttons.forEach(x=>x.disabled=true);answerButton.classList.add('correct','repaired');answerButton.innerHTML=`<del>${esc(q.wrongChar)}</del><ins>${esc(q.correctChar)}</ins>`;recordGameAnswer(type,ok);$('#gameFeedback').innerHTML=ok?`找到了！“<b>${esc(q.wrongChar)}</b>”应该是“<b>${esc(q.correctChar)}</b>”。`:`正确位置在这里：“<b>${esc(q.wrongChar)}</b>”应该是“<b>${esc(q.correctChar)}</b>”。`;showGameNext(type)});document.querySelectorAll('[data-game-answer]').forEach(b=>b.onclick=()=>{if(g.answered||b.disabled)return;let ok=b.dataset.correct==='true';if(!ok&&!g.attempts){g.attempts=1;b.disabled=true;b.classList.add('gentle');$('#gameFeedback').textContent=`先不给答案。${q.tip} 再试一次。`;save();return}document.querySelectorAll('[data-game-answer]').forEach(x=>{x.disabled=true;if(x.dataset.correct==='true')x.classList.add('correct')});recordGameAnswer(type,ok);$('#gameFeedback').innerHTML=ok?'答对了！轻轻收下一片诗叶。':`先看正确答案：<b>${esc(q.answer)}</b>`;showGameNext(type)});let selected=[],answer=q.answer?.split('|')||[];document.querySelectorAll('[data-game-order]').forEach(b=>b.onclick=()=>{if(g.answered||b.disabled)return;const expected=answer[selected.length];if(b.dataset.gameOrder!==expected){g.attempts++;b.classList.add('gentle');$('#gameFeedback').innerHTML=`这句还没到这里。下一句是“<b>${esc(expected)}</b>”，再试一次。`;setTimeout(()=>b.classList.remove('gentle'),650);return}selected.push(b.dataset.gameOrder);b.classList.add('correct');setOrderUI(selected,$('#gameOrderTarget'),'[data-game-order]');$('#gameFeedback').textContent=selected.length===answer.length?'顺序全对，诗词拼图完成！':`第 ${selected.length} 句正确。`;if(selected.length===answer.length){recordGameAnswer(type,true);showGameNext(type)}});if($('#gameOrderUndo'))$('#gameOrderUndo').onclick=()=>{if(g.answered)return;selected.pop();setOrderUI(selected,$('#gameOrderTarget'),'[data-game-order]')};if($('#gameOrderReset'))$('#gameOrderReset').onclick=()=>{if(g.answered)return;selected=[];setOrderUI(selected,$('#gameOrderTarget'),'[data-game-order]')}}
function bindStudio(){let mood='安静';$('#studioPoem').onchange=()=>go(`studio/${$('#studioPoem').value}`);document.querySelectorAll('[data-palette]').forEach(b=>b.onclick=()=>{document.querySelector('.studio-canvas').className=`studio-canvas palette-${b.dataset.palette}`});document.querySelectorAll('[data-studio-mood]').forEach(b=>b.onclick=()=>{mood=b.dataset.studioMood;document.querySelectorAll('[data-studio-mood]').forEach(x=>x.classList.toggle('selected',x===b))});$('#studioText').oninput=()=>{$('#studioNote').textContent=$('#studioText').value||'我在这首诗里看见了……'};$('#saveCreation').onclick=()=>{state.creations.push({date:new Date().toISOString(),poemId:$('#studioPoem').value,mood,text:$('#studioText').value});save();$('#studioFeedback').textContent='作品卡已经保存在这台设备。'};$('#printCreation').onclick=()=>print()}

render();
setTimeout(()=>{let main=$('#main');if(document.visibilityState==='visible'&&main){let tip=document.createElement('aside');tip.className='rest-reminder';tip.textContent='眼睛休息一下：看看远处，喝口水，再决定要不要继续。';main.append(tip)}},state.settings.minutes*60000);
if('speechSynthesis'in window)speechSynthesis.addEventListener('voiceschanged',()=>{chineseVoice=null});
if('serviceWorker'in navigator){navigator.serviceWorker.addEventListener('controllerchange',()=>{if(sessionStorage.getItem('sw-notice-v29'))return;sessionStorage.setItem('sw-notice-v29','1');let tip=document.createElement('div'),button=document.createElement('button');tip.className='offline-ready update-ready';tip.append('✓ 新版已准备好 ');button.textContent='刷新使用';button.onclick=()=>location.reload();tip.append(button);document.body.append(tip)});navigator.serviceWorker.register('/sw.js?v=29',{updateViaCache:'none'}).then(async reg=>{reg.update();await navigator.serviceWorker.ready;if(!sessionStorage.getItem('offline-ready-v29')){sessionStorage.setItem('offline-ready-v29','1');let tip=document.createElement('div');tip.className='offline-ready';tip.textContent='✓ 离线诗词冒险已准备好';document.body.append(tip);setTimeout(()=>tip.remove(),2400)}}).catch(()=>{})}
