import {poems,masteryNames} from './poems.js'; import {scheduleReview,createDailyTasks} from './review.js'; import {storage} from './storage.js'; import {gameModes,createGameRound,pointsForAnswer,levelForPoints} from './games.js';
let state=storage.load(), route=location.hash.slice(1)||'home', session={};
const $=s=>document.querySelector(s), esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const save=()=>storage.save(state); const go=r=>{location.hash=r};
addEventListener('hashchange',()=>{route=location.hash.slice(1)||'home';render()});
const icon=(p,i=0)=>`<div class="scene" role="img" aria-label="${p.images[i%p.images.length].alt}"><span>${p.images[i%p.images.length].emoji}</span><small>${p.imagery[i%p.imagery.length]}</small></div>`;
function nav(){let points=state.rewards?.points||0;return `<header><a class="brand" href="#home"><span>🌱</span>诗画小书童</a><nav aria-label="主导航"><a href="#today">今日闯关</a><a href="#map">诗词地图</a><a href="#games">游戏馆</a><a href="#tree">诗词树</a><a href="#parent">家长</a><a href="#settings">设置</a></nav><a class="points-pill" href="#tree" aria-label="查看诗叶积分">🍃 ${points}</a></header>`}
function shell(content,title=''){return `${nav()}<main id="main" class="container ${state.settings.font==='large'?'large':''}">${title?`<h1>${title}</h1>`:''}${content}</main><footer>所有学习数据仅保存在本浏览器 · 不收集儿童真实身份</footer>`}
function home(){return shell(`<section class="hero"><div><span class="eyebrow">给 7—9 岁孩子的古诗记忆花园</span><h1>每天 10 分钟，<br><em>把诗种进心里</em></h1><p>复习旧诗、学会新诗、用画面和游戏记得更牢。</p><div class="actions"><a class="button primary" href="#${state.profile?'today':'onboarding'}">开始今天的闯关</a><a class="button" href="#map">进入诗词地图</a><a class="button ghost" href="#parent">家长查看进度</a></div></div><div class="hero-art" aria-label="生长中的诗词树">🌿<span>📖</span></div></section><section class="promise"><div>👀<b>先看懂画面</b><span>把诗句变成脑海里的小电影</span></div><div>🎧<b>再听读背诵</b><span>逐句听、轻声读、勇敢背</span></div><div>🌱<b>按时再相遇</b><span>在快忘记时，刚好复习</span></div></section>`)}
function onboarding(){let step=session.onboardStep||1;return shell(`<section class="narrow card"><div class="steps">${[1,2,3].map(x=>`<i class="${x<=step?'on':''}">${x}</i>`).join('')}</div>${step===1?`<h1>小书童怎么称呼你？</h1><label>昵称（不用真实姓名）<input id="nickname" maxlength="8" placeholder="例如：小竹子"></label>`:step===2?`<h1>现在读几年级？</h1><div class="choice">${[1,2,3].map(g=>`<button data-grade="${g}" class="${session.grade===g?'selected':''}">${g} 年级</button>`).join('')}</div>`:`<h1>选一个学习目标</h1><div class="choice vertical"><button data-goal="复习一二年级 + 预习三年级" class="selected">复习一二年级 + 预习三年级<small>推荐给二升三</small></button><button data-goal="跟着当前年级巩固">跟着当前年级巩固</button></div>`}<div class="actions"><button id="onboardNext" class="primary">${step===3?'开启诗词之旅':'下一步'}</button></div></section>`,'')}
function ensureDaily(){const day=new Date().toISOString().slice(0,10);if(!state.daily||state.daily.date!==day){state.daily={date:day,tasks:createDailyTasks(poems,state.progress,state.settings.taskCount)};save()}}
function today(){if(!state.profile)return onboarding();ensureDaily();let done=state.daily.tasks.filter(t=>t.done).length;return shell(`<section class="page-head"><div><span class="eyebrow">${esc(state.profile.nickname)}的小任务</span><h1>今天走四小步</h1><p>预计 ${state.settings.minutes-2}—${state.settings.minutes+2} 分钟，完成一项就让叶子亮起来。</p></div><div class="ring">${done}<small>/${state.daily.tasks.length}</small></div></section><div class="task-list">${state.daily.tasks.map((t,i)=>{let p=poems.find(x=>x.id===t.poemId);return `<article class="task ${t.done?'done':''}"><span class="task-no">${t.done?'✓':i+1}</span>${icon(p,i)}<div><span>${t.kind}</span><h2>${p.title}</h2><p>${p.dynasty} · ${p.author}</p></div><a class="button ${i===done?'primary':''}" href="#learn/${p.id}">${t.done?'再练一次':'开始'}</a></article>`}).join('')}</div>`)}
function mapPage(){return shell(`<section class="filters" aria-label="筛选诗词"><select id="gradeFilter" aria-label="按年级"><option value="all">全部年级</option>${[1,2,3].map(g=>`<option value="${g}">${g} 年级</option>`).join('')}</select><select id="termFilter" aria-label="按学期"><option value="all">全部学期</option><option>上</option><option>下</option></select><select id="statusFilter" aria-label="按状态"><option value="all">全部状态</option>${masteryNames.map((x,i)=>`<option value="${i}">${x}</option>`).join('')}</select></section><div id="poemGrid" class="grid">${poemCards(poems)}</div>`,'诗词地图')}
function poemCards(list){return list.map(p=>{let level=state.progress[p.id]?.level||0;return `<article class="poem-card" data-grade="${p.grade}" data-term="${p.semester}" data-status="${level}">${icon(p)}<span class="status s${level}">${masteryNames[level]}</span><h2>${p.title}</h2><p>${p.dynasty} · ${p.author}</p><small>${p.grade} 年级${p.semester}册 · ${p.theme}</small><a class="button" href="#learn/${p.id}">${level?'继续学习':'去认识'}</a></article>`}).join('')}
function learn(id){let p=poems.find(x=>x.id===id)||poems[0], step=session.learn?.id===id?session.learn.step:1;session.learn={id,step,hints:session.learn?.hints||0,score:session.learn?.score||0};let body='';
 if(step===1)body=`<h2>先观察：这幅画藏着哪首诗？</h2><div class="scene-row">${p.images.slice(0,4).map((_,i)=>icon(p,i)).join('')}</div><div class="choice vertical">${[p.title,...poems.filter(x=>x.id!==id).slice(0,2).map(x=>x.title)].sort().map(x=>`<button data-answer="${esc(x)}">${x}</button>`).join('')}</div>`;
 if(step===2)body=`<h2>听一听，诗句会发光</h2><div class="poem-lines">${p.lines.map((x,i)=>`<p data-line="${i}">${state.settings.pinyin?`<ruby>${x}<rt>${p.pinyin[i]}</rt></ruby>`:x}<button class="speak-line" data-i="${i}" aria-label="朗读第${i+1}句">▶</button></p>`).join('')}</div><div class="actions"><button id="speakAll" class="primary">▶ 完整朗读</button><button id="slow">🐢 慢速</button><button id="stopSpeak">暂停</button></div>`;
 if(step===3)body=`<h2>诗里有一幅怎样的画？</h2><div class="explain-list">${p.lines.map((x,i)=>`<button class="explain"><b>${p.imagery[i]}</b><span>${p.explanations[i]}</span></button>`).join('')}</div>`;
 if(step===4){let shuffled=[...p.lines].sort((a,b)=>a.localeCompare(b));body=`<h2>点一点，把诗句排回家</h2><p class="soft">依次点击诗句；也可以用键盘操作。</p><div id="orderTarget" class="order-target"></div><div id="orderChoices" class="choice vertical">${shuffled.map(x=>`<button data-order="${esc(x)}">${x}</button>`).join('')}</div>`}
 if(step===5)body=`<h2>关键词悄悄藏起来了</h2><p class="soft">想不起来可以看提示，提示越少星星越多。</p><div class="poem-lines blanks">${p.lines.map((x,i)=>`<p>${x.replace(p.imagery[i]||x.slice(0,2),'＿＿')}</p>`).join('')}</div><button id="hint">💡 看一次提示</button><div id="hintText" aria-live="polite"></div>`;
 if(step===6)body=`<h2>轮到你来背啦</h2><p>录音只留在当前页面，不会上传。拒绝权限也可以直接自评。</p><div class="recorder"><div id="mic">🎙️</div><button id="record" class="primary">开始录音</button><button id="playback" disabled>回放</button></div><p id="recordStatus" aria-live="polite">准备好后再开始，不着急。</p><button id="selfDone">我已背完</button>`;
 if(step===7){let stars=Math.max(1,3-Math.floor(session.learn.hints/2));body=`<div class="complete"><div class="reward">${'⭐'.repeat(stars)}</div><h2>一片新叶长出来了！</h2><p>本次提示 ${session.learn.hints} 次。${session.learn.hints>2?'明天再看看容易卡住的句子。':'你已经把画面和诗句连起来了。'}</p><div class="summary"><span>得分<b>${70+stars*10}</b></span><span>新叶片<b>+1</b></span></div><a class="button primary" href="#today">回到今日闯关</a></div>`}
 return shell(`<div class="learn-top"><a href="#map">← 暂时离开</a><div class="bar"><i style="width:${step/7*100}%"></i></div><b>${step}/7</b></div><article class="learning card"><span class="eyebrow">${p.title} · 第 ${step} 步</span>${body}${step<7?`<div class="actions end"><button id="learnNext" class="primary">${step===6?'完成练习':'继续下一步'}</button></div>`:''}</article>`)}
function games(){let points=state.rewards?.points||0,level=levelForPoints(points);return shell(`<section class="game-hero"><div><span class="eyebrow">每日 5—10 分钟</span><h1>今天想玩哪一种？</h1><p>每局 8 题，由易到难。答错的题会在结尾再来一次。</p></div><div class="reward-mini"><b>${level.icon} ${level.name}</b><span>🍃 ${points} 诗叶积分</span></div></section><div class="grid games">${gameModes.map((d,i)=>`<article class="game-card ${i===0?'featured':''}"><span>${d.icon}</span><div class="difficulty">${i===0?'综合推荐':'8 题 · 约 5 分钟'}</div><h2>${d.title}</h2><p>${d.desc}</p><a class="button primary" href="#play/${d.id}">开始闯关</a></article>`).join('')}</div>`)}
function ensureGame(type){if(session.game?.type!==type){session.game={type,questions:createGameRound(type,poems,8,state.activities.length%poems.length),index:0,score:0,points:0,wrong:[],answered:false,review:false,startedAt:Date.now()}}}
function play(type){ensureGame(type);let g=session.game;if(g.index>=g.questions.length)return gameResult();let q=g.questions[g.index],p=poems.find(x=>x.id===q.poemId),difficulty=g.index<3?'暖身':g.index<6?'进阶':'挑战';return shell(`<section class="narrow card game-play"><div class="game-status"><span>${g.review?'错题再见面':difficulty}</span><b>${g.index+1}/${g.questions.length}</b><span>🍃 +${g.points}</span></div><div class="bar"><i style="width:${g.index/g.questions.length*100}%"></i></div>${icon(p)}<span class="eyebrow">${p.title} · ${gameModes.find(x=>x.id===q.type)?.title||'小挑战'}</span><h1>${q.prompt}</h1><div class="choice vertical">${q.options.map(x=>`<button data-game-answer="${esc(x)}" data-correct="${x===q.answer}">${x}</button>`).join('')}</div><p id="gameFeedback" aria-live="polite"></p><div id="gameActions" class="actions end"></div><a class="button ghost" href="#games">暂时离开</a></section>`)}
function gameResult(){let g=session.game,accuracy=Math.round(g.score/Math.max(1,g.questions.length)*100),bonus=g.wrong.length===0?20:10,total=g.points+bonus;return shell(`<section class="narrow card complete game-result"><div class="reward">${accuracy>=80?'🌸':'🌿'}</div><span class="eyebrow">完成一局 · 约 ${Math.max(5,Math.round((Date.now()-g.startedAt)/60000))} 分钟</span><h1>${accuracy>=80?'诗句接得真稳！':'每一次想起来都算成长'}</h1><div class="summary"><span>答对率<b>${accuracy}%</b></span><span>本局积分<b>+${total}</b></span><span>回顾错题<b>${g.wrong.length}</b></span></div><p>${g.wrong.length?'错题已经重新见过一遍，下次会更熟。':'全对奖励再加 20 片诗叶！'}</p><div class="actions"><button id="playAgain" class="primary">再玩一局</button><a class="button" href="#games">选择其他游戏</a><a class="button ghost" href="#tree">看看成长</a></div></section>`)}
function tree(){let learned=Object.values(state.progress).filter(x=>x.level),solid=Object.values(state.progress).filter(x=>x.level===5).length,days=new Set(state.activities.map(x=>x.date?.slice(0,10))).size,rewards=state.rewards||{},level=levelForPoints(rewards.points||0);return shell(`<section class="tree-wrap"><div class="tree-art" aria-label="诗词成长树">${Array.from({length:Math.max(1,Math.min(12,Math.ceil((rewards.points||0)/25)))},(_,i)=>`<i style="--i:${i}">🍃</i>`).join('')}<b>🌳</b></div><div><span class="eyebrow">我的成长</span><h1>${level.icon} ${level.name}</h1><p>认真学习得到诗叶，诗叶会让小树慢慢长大。</p><div class="points-total">🍃 <b>${rewards.points||0}</b><span>诗叶积分</span></div><div class="stats"><span><b>${days}</b>学习天数</span><span><b>${rewards.gamesCompleted||0}</b>完成游戏</span><span><b>${rewards.poemsCompleted||0}</b>学完诗词</span></div><h2>成长徽章</h2><div class="badges"><span class="${(rewards.points||0)>=20?'earned':''}">🌱 第一捧诗叶</span><span class="${(rewards.gamesCompleted||0)>=3?'earned':''}">🏮 闯关小能手</span><span class="${(rewards.poemsCompleted||0)>=3?'earned':''}">🌸 三诗花开</span><span class="${(rewards.points||0)>=250?'earned':''}">🪶 花开小诗人</span></div></div></section>`)}
function parent(){let acts=state.activities, byDay=Array.from({length:7},(_,i)=>{let d=new Date();d.setDate(d.getDate()-(6-i));let key=d.toISOString().slice(0,10);return {key,count:acts.filter(a=>a.date?.startsWith(key)).length}}), levels=masteryNames.map((_,i)=>Object.values(state.progress).filter(p=>p.level===i).length), errors=Object.entries(state.progress).filter(([,p])=>p.errors?.length||p.hints>2).slice(0,3);return shell(`<section class="parent-grid"><article class="card"><h2>近 7 天学习趋势</h2><div class="chart">${byDay.map(d=>`<div><i style="height:${Math.max(8,d.count*24)}px"></i><small>${d.key.slice(5)}</small></div>`).join('')}</div></article><article class="card"><h2>掌握等级分布</h2><div class="levels">${levels.map((n,i)=>`<p><span>${masteryNames[i]}</span><i><b style="width:${poems.length?n/poems.length*100:0}%"></b></i><strong>${n}</strong></p>`).join('')}</div></article><article class="card"><h2>需要多看一眼</h2>${errors.length?errors.map(([id,p])=>`<p><b>${poems.find(x=>x.id===id)?.title}</b> · ${p.errors?.[0]||'提示使用较多'}<br><small>下次复习：${new Date(p.nextReviewAt).toLocaleDateString('zh-CN')}</small></p>`).join(''):'<p class="soft">完成几次练习后，这里会出现真实的易错诗句。</p>'}</article><article class="card advice"><h2>今天这样陪</h2><p>先让孩子说出画面，再背诗句。卡住时可以说：“你不是忘了整首诗，我们从上一幅画面接起来。”</p></article></section>`,'家长中心')}
function settings(){let s=state.settings;return shell(`<section class="narrow card form"><label><span>音效</span><input id="sound" type="checkbox" ${s.sound?'checked':''}></label><label><span>背景音乐</span><input id="music" type="checkbox" ${s.music?'checked':''}></label><label><span>显示拼音</span><input id="pinyin" type="checkbox" ${s.pinyin?'checked':''}></label><label><span>字体大小</span><select id="font"><option value="normal">标准</option><option value="large" ${s.font==='large'?'selected':''}>大字</option></select></label><label><span>学习时长提醒</span><select id="minutes">${[8,10,12,15].map(x=>`<option ${s.minutes===x?'selected':''}>${x}</option>`).join('')}</select></label><label><span>每日任务数</span><select id="taskCount">${[3,4,5].map(x=>`<option ${s.taskCount===x?'selected':''}>${x}</option>`).join('')}</select></label><button id="saveSettings" class="primary">保存设置</button><button id="clearData" class="danger">清空本地进度</button></section>`,'设置')}
function render(){let [page,id]=route.split('/');let views={home,onboarding,today,map:mapPage,games,play:()=>play(id),tree,parent,settings,learn:()=>learn(id)};$('#app').innerHTML=(views[page]||home)();bind(page,id)}
function finishLearning(id){let p=state.progress[id]||{};state.progress[id]=scheduleReview(p,{correct:session.learn.hints<=2,hints:session.learn.hints});state.activities.push({date:new Date().toISOString(),poemId:id,type:'learning',score:Math.max(60,100-session.learn.hints*10),points:30});state.rewards=state.rewards||{};state.rewards.points=(state.rewards.points||0)+30;state.rewards.poemsCompleted=(state.rewards.poemsCompleted||0)+1;state.rewards.minutesLearned=(state.rewards.minutesLearned||0)+8;ensureDaily();let t=state.daily.tasks.find(x=>x.poemId===id&&!x.done);if(t)t.done=true;save()}
 function bind(page,id){if(page==='onboarding'){document.querySelectorAll('[data-grade]').forEach(b=>b.onclick=()=>{session.grade=+b.dataset.grade;render()});document.querySelectorAll('[data-goal]').forEach(b=>b.onclick=()=>{session.goal=b.dataset.goal;render()});$('#onboardNext').onclick=()=>{let step=session.onboardStep||1;if(step===1){let n=$('#nickname').value.trim();if(!n){$('#nickname').focus();return}session.nickname=n}if(step===2&&!session.grade)return; if(step===3){state.profile={nickname:session.nickname,grade:session.grade,goal:session.goal||'复习一二年级 + 预习三年级',avatar:'🌱'};save();go('today');return}session.onboardStep=step+1;render()}}
 if(page==='map'){['grade','term','status'].forEach(k=>$(`#${k}Filter`).onchange=filterCards)}
 if(page==='learn'){let p=poems.find(x=>x.id===id);document.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{b.classList.add(b.dataset.answer===p.title?'correct':'gentle');if(b.dataset.answer!==p.title)session.learn.hints++});document.querySelectorAll('.speak-line').forEach(b=>b.onclick=()=>speak(p.lines[+b.dataset.i],.75));if($('#speakAll'))$('#speakAll').onclick=()=>speak(`${p.title}，${p.dynasty}，${p.author}。${p.lines.join('。')}`,session.slow?.6:.85);if($('#slow'))$('#slow').onclick=()=>{session.slow=!session.slow;$('#slow').classList.toggle('selected')};if($('#stopSpeak'))$('#stopSpeak').onclick=()=>speechSynthesis.cancel();let selected=[];document.querySelectorAll('[data-order]').forEach(b=>b.onclick=()=>{selected.push(b.dataset.order);b.disabled=true;$('#orderTarget').innerHTML=selected.map(x=>`<span>${x}</span>`).join('');if(selected.length===p.lines.length&&selected.join('|')!==p.lines.join('|')){session.learn.hints++;$('#orderTarget').classList.add('gentle')}});if($('#hint'))$('#hint').onclick=()=>{session.learn.hints++;$('#hintText').textContent=p.lines.join(' ｜ ')};setupRecorder();if($('#selfDone'))$('#selfDone').onclick=()=>{$('#recordStatus').textContent='完成啦！你的自评已经记录。'};if($('#learnNext'))$('#learnNext').onclick=()=>{if(session.learn.step===6)finishLearning(id);session.learn.step++;render()}}
 if(page==='play'){let g=session.game;if(g.index>=g.questions.length){$('#playAgain').onclick=()=>{session.game=null;render()}}else document.querySelectorAll('[data-game-answer]').forEach(b=>b.onclick=()=>{if(g.answered)return;g.answered=true;let q=g.questions[g.index],ok=b.dataset.correct==='true';document.querySelectorAll('[data-game-answer]').forEach(x=>{x.disabled=true;if(x.dataset.correct==='true')x.classList.add('correct')});b.classList.add(ok?'correct':'gentle');if(ok){g.score++;g.points+=pointsForAnswer(true,g.review?2:1);$('#gameFeedback').textContent='接得真稳！诗叶已经放进小篮子。'}else{g.wrong.push(q);$('#gameFeedback').innerHTML=`再看一眼：${esc(q.tip)}<br><b>正确答案：${esc(q.answer)}</b>`}let p=poems.find(x=>x.id===q.poemId);state.activities.push({date:new Date().toISOString(),poemId:p.id,type:`game-${id}`,score:ok?100:60,correct:ok});state.progress[p.id]=scheduleReview(state.progress[p.id],{correct:ok,hints:ok?0:1});save();$('#gameActions').innerHTML='<button id="nextGame" class="primary">下一题</button>';$('#nextGame').onclick=()=>{g.index++;g.answered=false;if(g.index===g.questions.length&&g.wrong.length&&!g.review){g.questions=[...g.questions,...g.wrong];g.review=true}if(g.index>=g.questions.length){let bonus=g.wrong.length===0?20:10,total=g.points+bonus;state.rewards=state.rewards||{};state.rewards.points=(state.rewards.points||0)+total;state.rewards.gamesCompleted=(state.rewards.gamesCompleted||0)+1;state.rewards.minutesLearned=(state.rewards.minutesLearned||0)+Math.max(5,Math.round((Date.now()-g.startedAt)/60000));state.activities.push({date:new Date().toISOString(),type:`game-complete-${id}`,score:Math.round(g.score/Math.max(1,g.questions.length)*100),points:total});save()}render()}})}if(page==='settings'){$('#saveSettings').onclick=()=>{['sound','music','pinyin'].forEach(k=>state.settings[k]=$(`#${k}`).checked);['minutes','taskCount'].forEach(k=>state.settings[k]=+$(`#${k}`).value);state.settings.font=$('#font').value;state.daily=null;save();go('home')};$('#clearData').onclick=()=>{if(confirm('确定清空这个浏览器里的全部学习记录吗？')){storage.clear();state=storage.load();go('home')}}}}
function filterCards(){document.querySelectorAll('.poem-card').forEach(c=>{c.hidden=!(($('#gradeFilter').value==='all'||c.dataset.grade===$('#gradeFilter').value)&&($('#termFilter').value==='all'||c.dataset.term===$('#termFilter').value)&&($('#statusFilter').value==='all'||c.dataset.status===$('#statusFilter').value))})}
function speak(text,rate=.85){if(!('speechSynthesis'in window))return alert('当前浏览器暂不支持语音朗读，你仍可继续阅读学习。');speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(text);u.lang='zh-CN';u.rate=rate;speechSynthesis.speak(u)}
function setupRecorder(){if(!$('#record'))return;let rec,chunks=[],url;$('#record').onclick=async()=>{if(!navigator.mediaDevices?.getUserMedia){$('#recordStatus').textContent='当前浏览器不支持录音，可以直接完成自评。';return}try{let stream=await navigator.mediaDevices.getUserMedia({audio:true});rec=new MediaRecorder(stream);rec.ondataavailable=e=>chunks.push(e.data);rec.onstop=()=>{url=URL.createObjectURL(new Blob(chunks));$('#playback').disabled=false;stream.getTracks().forEach(t=>t.stop())};rec.start();$('#recordStatus').textContent='正在录音…背完后点“停止录音”。';$('#record').textContent='停止录音';$('#record').onclick=()=>{rec.stop();$('#record').textContent='已录好'}}catch{$('#recordStatus').textContent='没有获得麦克风权限，没关系，可以直接完成自评。'}};$('#playback').onclick=()=>url&&new Audio(url).play()}
render();
