const q=(id,type,prompt,answer,options,line=0)=>({id,type,prompt,answer,options,difficulty:1,ability:type==='order'?'memory':'recognition',explanation:'先在脑海里想一想诗中的画面，再作答。',hint:'轻声读一遍相关诗句。',line});
export const poems=[
['jing-ye-si','静夜思','唐','李白',1,'上','课内',['床前明月光','疑是地上霜','举头望明月','低头思故乡'],['chuáng qián míng yuè guāng','yí shì dì shàng shuāng','jǔ tóu wàng míng yuè','dī tóu sī gù xiāng'],['月光洒在床前','像地上铺了一层白霜','抬头望着明月','低头想念家乡'],['明月','白霜','故乡'],'秋','思乡'],
['chun-xiao','春晓','唐','孟浩然',1,'下','课内',['春眠不觉晓','处处闻啼鸟','夜来风雨声','花落知多少'],['chūn mián bù jué xiǎo','chù chù wén tí niǎo','yè lái fēng yǔ shēng','huā luò zhī duō shǎo'],['春天睡得香，不知天亮了','到处传来鸟叫声','昨夜听见风雨声','不知道花落了多少'],['春眠','啼鸟','风雨','落花'],'春','惜春'],
['cun-ju','村居','清','高鼎',1,'下','课内',['草长莺飞二月天','拂堤杨柳醉春烟','儿童散学归来早','忙趁东风放纸鸢'],['cǎo zhǎng yīng fēi èr yuè tiān','fú dī yáng liǔ zuì chūn yān','ér tóng sàn xué guī lái zǎo','máng chèn dōng fēng fàng zhǐ yuān'],['早春草长，黄莺飞舞','杨柳轻拂堤岸','孩子们早早放学回家','趁着东风放风筝'],['黄莺','杨柳','儿童','纸鸢'],'春','童趣'],
['xiao-chi','小池','宋','杨万里',1,'下','课内',['泉眼无声惜细流','树阴照水爱晴柔','小荷才露尖尖角','早有蜻蜓立上头'],['quán yǎn wú shēng xī xì liú','shù yīn zhào shuǐ ài qíng róu','xiǎo hé cái lù jiān jiān jiǎo','zǎo yǒu qīng tíng lì shàng tóu'],['泉水静静流出','树影映在柔和水面','小荷刚露出尖角','蜻蜓早已停在上面'],['泉眼','树阴','小荷','蜻蜓'],'夏','自然'],
['chi-le-ge','敕勒歌','南北朝','北朝民歌',2,'上','课内',['敕勒川，阴山下','天似穹庐，笼盖四野','天苍苍，野茫茫','风吹草低见牛羊'],['chì lè chuān yīn shān xià','tiān sì qióng lú lǒng gài sì yě','tiān cāng cāng yě máng máng','fēng chuī cǎo dī xiàn niú yáng'],['敕勒草原在阴山脚下','天空像大毡房罩住原野','蓝天辽阔，草原无边','风吹低草，露出牛羊'],['阴山','穹庐','原野','牛羊'],'夏','边塞'],
['deng-guan-que-lou','登鹳雀楼','唐','王之涣',2,'上','课内',['白日依山尽','黄河入海流','欲穷千里目','更上一层楼'],['bái rì yī shān jìn','huáng hé rù hǎi liú','yù qióng qiān lǐ mù','gèng shàng yì céng lóu'],['夕阳靠着山落下','黄河奔向大海','想看得更远','就再登上一层楼'],['白日','黄河','千里目','楼'],'秋','励志'],
['wang-lu-shan-pu-bu','望庐山瀑布','唐','李白',2,'上','课内',['日照香炉生紫烟','遥看瀑布挂前川','飞流直下三千尺','疑是银河落九天'],['rì zhào xiāng lú shēng zǐ yān','yáo kàn pù bù guà qián chuān','fēi liú zhí xià sān qiān chǐ','yí shì yín hé luò jiǔ tiān'],['阳光照山，升起紫色云霞','远看瀑布像挂在山前','水流从高处飞泻而下','好像银河从天落下'],['香炉峰','紫烟','瀑布','银河'],'夏','山水'],
['jue-ju','绝句','唐','杜甫',2,'下','课内',['两个黄鹂鸣翠柳','一行白鹭上青天','窗含西岭千秋雪','门泊东吴万里船'],['liǎng gè huáng lí míng cuì liǔ','yì háng bái lù shàng qīng tiān','chuāng hán xī lǐng qiān qiū xuě','mén bó dōng wú wàn lǐ chuán'],['黄鹂在翠绿柳树间歌唱','一行白鹭飞上蓝天','窗中像装着西岭积雪','门外停着远来的船'],['黄鹂','白鹭','西岭','船'],'春','山水'],
['fu-de-gu-yuan-cao','赋得古原草送别（节选）','唐','白居易',2,'下','课内',['离离原上草','一岁一枯荣','野火烧不尽','春风吹又生'],['lí lí yuán shàng cǎo','yí suì yì kū róng','yě huǒ shāo bú jìn','chūn fēng chuī yòu shēng'],['原野上青草茂盛','每年枯萎又繁茂','野火也烧不完','春风吹来又生长'],['原上草','枯荣','野火','春风'],'春','生命'],
['shan-xing','山行','唐','杜牧',3,'上','课内',['远上寒山石径斜','白云生处有人家','停车坐爱枫林晚','霜叶红于二月花'],['yuǎn shàng hán shān shí jìng xié','bái yún shēng chù yǒu rén jiā','tíng chē zuò ài fēng lín wǎn','shuāng yè hóng yú èr yuè huā'],['石路弯弯伸向秋山','白云升起处住着人家','因为喜爱晚秋枫林而停车','霜叶比春花还红'],['寒山','白云','枫林','霜叶'],'秋','山水'],
['ye-shu-suo-jian','夜书所见','宋','叶绍翁',3,'上','课内',['萧萧梧叶送寒声','江上秋风动客情','知有儿童挑促织','夜深篱落一灯明'],['xiāo xiāo wú yè sòng hán shēng','jiāng shàng qiū fēng dòng kè qíng','zhī yǒu ér tóng tiǎo cù zhī','yè shēn lí luò yì dēng míng'],['梧桐叶发出秋日寒声','江上秋风勾起思乡情','知道孩子们在捉蟋蟀','深夜篱笆旁亮着灯'],['梧叶','秋风','儿童','灯'],'秋','思乡'],
['wang-tian-men-shan','望天门山','唐','李白',3,'上','课内',['天门中断楚江开','碧水东流至此回','两岸青山相对出','孤帆一片日边来'],['tiān mén zhōng duàn chǔ jiāng kāi','bì shuǐ dōng liú zhì cǐ huí','liǎng àn qīng shān xiāng duì chū','gū fān yí piàn rì biān lái'],['长江冲开天门山','碧水到这里回旋','两岸青山迎面出现','一叶孤帆从日边驶来'],['天门山','碧水','青山','孤帆'],'夏','山水']
].map(p=>{const [id,title,dynasty,author,grade,semester,source,lines,pinyin,explanations,images,season,theme]=p;return {id,title,dynasty,author,grade,semester,edition:'统编版示例',source,required:true,lines,pinyin,explanations,images:images.map((x,i)=>({emoji:['🌙','🌿','🕊️','⛵'][i],alt:`${title}中的${x}`})),imagery:images,season,theme,audioUrl:null,learning:{steps:7},questions:[q(`${id}-title`,'title',`哪首诗写到了“${images[0]}”？`,title,[title,'静夜思','春晓']),q(`${id}-line`,'next',`“${lines[0]}”的下一句是？`,lines[1],[lines[1],lines[2],lines[3]],1),q(`${id}-author`,'author',`《${title}》的作者是？`,author,[author,'李白','杜甫']),q(`${id}-order`,'order','把诗句排成正确顺序',lines.join('|'),[...lines].reverse())]};});
export const masteryNames=['未开始','见过','熟悉','会接句','会背','长期掌握'];
